version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run:
          name: Install dependency
          command: yarn
      - run:
          name: Check linter
          command: yarn lint:check
      - run:
          name: Build application
          command: yarn build
      - run:
          name: Test
          command: yarn test

workflows:
  build_and_test:
    jobs:
      - test